import argparse
import logging
import os
from typing import Optional

from isdleda.launchers.launcher_utils import MemAccess, init_logger
from isdleda.utils.export.export import load_from_pickle
from isdleda.utils.paths import (ISD_VALUES_FILE_PKL, OUT_FILE_FORMULA,
                                 OUT_FILES_CEB_DIR)

LOGGER = logging.getLogger(__name__)


def parse_arguments():
    parser = argparse.ArgumentParser("Launch values cleaner")
    parser.add_argument(
        "--clean-oor",
        action="store_true",
        help="Delete all the files inside out dir that are not present in the "
        "isd_values range."
        "They may have been generated by previous (erroneous) run of the tool."
    )
    parser.add_argument(
        "--clean-wrong",
        action="store_true",
        help=
        ("Delete all the files inside out dir that have wrong values (e.g. k<r)."
         "They may have been generated by previous (erroneous) run of the tool."
         ))
    return parser


def _clean_wrong_values(out_type: str, files_ext: str):
    acc = 0
    for mem_access in MemAccess:
        directory = OUT_FILES_CEB_DIR.format(out_type=out_type,
                                             memaccess=mem_access.name)
        for filename in filter(lambda x: not x.startswith(OUT_FILE_FORMULA),
                               os.listdir(directory)):
            ff = filename[:-(len(files_ext) + 1)]
            n, r, _ = ff.split('_')
            if int(r) / int(n) > .5:
                os.remove(os.path.join(directory, filename))
                acc += 1
    return acc


def _clean_oor_values(out_type: str, files_ext: str):
    isd_values_ok = load_from_pickle(ISD_VALUES_FILE_PKL)
    isd_values_ok_hashed = set(f"{val.n}_{val.r}_{val.t}.{files_ext}"
                               for val in isd_values_ok)
    acc = 0
    for mem_access in MemAccess:
        directory = OUT_FILES_CEB_DIR.format(out_type=out_type,
                                             memaccess=mem_access.name)
        for filename in filter(lambda x: not x.startswith(OUT_FILE_FORMULA),
                               os.listdir(directory)):
            if filename not in isd_values_ok_hashed:
                input(filename)
                acc += 1
                # input(filename)
                # os.remove(os.path.join(OUT_FILES_CEB_DIR, filename))
    return acc


def main(raw_args: Optional[list[str]] = None):
    print("#" * 80)
    init_logger(LOGGER, 'logs/cisd.log')
    parser = parse_arguments()
    if raw_args and len(raw_args) != 0:
        namespace = parser.parse_args(raw_args)
    else:
        namespace = parser.parse_args()

    out_type = 'pkl' if namespace.out_format == 'bin' else namespace.out_format
    match out_type:
        case 'bin':
            file_ext = 'pkl'
        case 'pkl':
            file_ext = 'pkl'
        case 'txt':
            file_ext = 'txt'
        case _:
            raise AttributeError(f"Wrong value for out_type: {out_type} ")

    if namespace.clean_wrong:
        dels = _clean_wrong_values(out_type, file_ext)
        print(f"Deleted {dels} wrong files")
    if namespace.clean_oor:
        dels = _clean_oor_values(out_type, file_ext)
        print(f"Deleted {dels} Out-Of-Range files")
    if namespace.clean_wrong or namespace.clean_oor:
        return


if __name__ == '__main__':
    main()
