"""Compute the computational cost for the quantum ISD
"""
import csv
import argparse
import functools
import logging
import os
import time
from dataclasses import replace
from enum import IntEnum
from multiprocessing import Pool
from typing import Dict, Optional, Sequence

from isdleda.launchers.launcher_utils import (argparse_check_positive,
                                              get_no_of_files, init_logger)
from isdleda.utils.common import ISDValue, dict_to_isd_value
from isdleda.utils.export.export import (load_from_json, load_from_pickle,
                                         save_to_json, save_to_pickle,
                                         save_to_txt)
from isdleda.utils.paths import (ISD_VALUES_FILE_JSON, OUT_FILES_QLB_DIR,
                                 OUT_FILES_QLB_FMT, OUT_FILES_QLB_SYMBOLIC)
# ISD_scripts
from measures.common import CodeExtended
from measures.leebrickell_quantum import LeeBrickellQuantum, ValueDicts
from sage.all import assume, var
# SAGE
from sage.rings.all import RealField
from utils.datamanipulation import replace_exp_valuedict

REAL_PREC = 1000
REAL_FIELD = RealField(prec=REAL_PREC)
LOGGER = logging.getLogger(__name__)

from statics.codes import SecurityLevels


class OutType(IntEnum):
    TXT = 0
    PKL = 1
    JSON = 2


def _get_formula():
    meas = LeeBrickellQuantum(CodeExtended(
        "LEDA",
        SecurityLevels.UND,
        -1,
        -1,
        -1,
        is_cyclic=False,
        init_real_values=False,
    ),
                              p=-1)
    res = meas.go()
    return res


def _store_formula(out: OutType, res):
    if out == OutType.TXT:
        save_to_txt(OUT_FILES_QLB_SYMBOLIC.format(out_type="txt"), res)
    elif out == OutType.PKL:
        save_to_pickle(OUT_FILES_QLB_SYMBOLIC.format(out_type="pkl"), res)
    else:  #
        save_to_json(OUT_FILES_QLB_SYMBOLIC.format(out_type="pkl"), res)


def _process_value(value, out_type, extension):
    out_file = OUT_FILES_QLB_FMT.format(
        out_type=out_type,
        n=value.n,
        r=value.r,
        t=value.t,
        ext=extension,
    )
    if os.path.isfile(out_file):
        LOGGER.info(f"{out_file} already existing, skipping")
        return False
    return True


def parse_arguments():

    parser = argparse.ArgumentParser("Launch Lee-Brickell")
    parser.add_argument('-p',
                        '--poolsize',
                        default=2,
                        # required=True,
                        type=argparse_check_positive,
                        help="Multiprocess pool size")
    parser.add_argument('--max-tasks',
                        type=argparse_check_positive,
                        help="Multiprocess max tasks per child",
                        default=1)
    parser.add_argument('--chunksize',
                        type=argparse_check_positive,
                        default=2,
                        help="Multiprocess chunk size")
    parser.add_argument("--skip-existing",
                        action="store_true",
                        help="Skip quantum complexity files if existing")
    parser.add_argument(
        "--in-format",
        choices=["tool_gen", "csv", "cli"],
        default="tool_gen",
        help=
        "tool_gen is the default file containing the ISD values generated by the parameter generation tool (list of ISDValue). Cli is a comma-separated list of values."
    )
    parser.add_argument(
        "--in-data",
        default=ISD_VALUES_FILE_JSON,
        help=
        "The input data. For csv and json it's a filename; for cli is an (n, k, t) value (comma separated). The default is the json file generated by the parameters generation tool."
    )

    parser.add_argument("--out-format",
                        choices=["txt", "pkl", "json", "stdout"],
                        default="pkl")
    parser.add_argument(
        "--formula-only",
        action="store_true",
        help="Just store the formula without computing the actual values",
    )
    return parser


def isd_compute(value, p_range, formula, out_dir, extension):
    n_o, k_o, t_o, r_o, p_o = var("n_o, k_o, t_o, r_o, p_o", domain="integer")
    assume(n_o > 0, k_o > 0, t_o > 0, r_o > 0, p_o > 0)
    var_subs = {
        n_o: REAL_FIELD(value.n),
        k_o: REAL_FIELD(value.n - value.r),
        r_o: REAL_FIELD(value.r),
        t_o: REAL_FIELD(value.t),
    }
    dic: Dict[str, ValueDicts] = {}
    t0 = time.perf_counter()
    for p in p_range:
        var_subs[p_o] = REAL_FIELD(p)
        # All the following value dicts are present, so if conditions are
        # not really necessary, but still they are in theory possibly None, and
        # lsp complains
        # if not (formula.normal2 and formula.normal_expanded2 and formula.tmeas2):
        #     raise Exception("Wrong state")
        normal2 = replace_exp_valuedict(formula.normal2,
                                        var_subs,
                                        numerical=True)
        normal_expanded2 = replace_exp_valuedict(formula.normal_expanded2,
                                                 var_subs,
                                                 numerical=True)
        tmeas2 = replace_exp_valuedict(formula.tmeas2,
                                       var_subs,
                                       numerical=True)
        res2 = replace(
            formula,
            in_params={
                n_o: value.n,
                k_o: value.n - value.r,
                r_o: value.r,
                t_o: value.t,
                p_o: p
            },
            normal2=normal2,
            normal_expanded2=normal_expanded2,
            tmeas2=tmeas2,
            normal=None,
            normal_expanded=None,
            tmeas=None,
        )
        dic[f"p_{p}"] = res2
    te = time.perf_counter()

    min_time = min(dic.items(), key=lambda algo: algo[1].tmeas2.t_depth)
    dic['MinimumDepth'] = min_time[1]
    if out_dir == 'stdout':
        print(dic)
    else:
        out_file = OUT_FILES_QLB_FMT.format(
            out_type=out_dir,
            n=value.n,
            k=value.n - value.r,
            t=value.t,
            ext=extension,
        )
        if out_dir == 'pkl':
            save_to_pickle(out_file, dic)
        elif out_dir == 'txt':
            save_to_txt(out_file, dic)
    te = time.perf_counter()
    return len(p_range), te - t0


def main(raw_args: Optional[list[str]] = None):
    init_logger(LOGGER, 'out/qisd.log')
    parser = parse_arguments()
    if raw_args and len(raw_args) != 0:
        namespace = parser.parse_args(raw_args)
    else:
        namespace = parser.parse_args()
    print(namespace)

    LOGGER.info(namespace)
    LOGGER.info("#" * 80)

    match namespace.out_format:
        case "txt":
            out_type_dir = "txt"
            file_ext = ".txt"
        case "pkl":
            out_type_dir = "pkl"
            file_ext = "pkl"
        case "json":
            raise argparse.ArgumentError(None,
                                         "JSON output not implemented yet")
        case "stdout":
            out_type_dir = "stdout"
            file_ext = ""
        case _:
            raise argparse.ArgumentError(None, "Invalid output")
    pickle_file = OUT_FILES_QLB_SYMBOLIC.format(out_type="pkl")
    if not os.path.isfile(pickle_file):
        res = _get_formula()
        # Formula always stored as pkl
        _store_formula(OutType.PKL, res)
    else:
        res = load_from_pickle(pickle_file)
        assert res is not None and len(res) > 0, f"No valid formula found"

    if namespace.formula_only:
        print(res)
        return

    # ISD values always stored as pkl
    match namespace.in_format:
        case "tool_gen":
            isd_values: Sequence[ISDValue] = [
                dict_to_isd_value(x) for x in load_from_json(namespace.in_data)
            ]
        case "cli":
            n, k, t = [int(x) for x in namespace.in_data.split(",")]
            isd_values = [ISDValue(n, n - k, t)]
        case "csv":
            isd_values: Sequence[ISDValue] = []
            with open(namespace.in_data, mode='r', newline='') as file:
                csv_reader = csv.reader(file)
            for row in csv_reader:
                n, k, t = map(int, row)
                isd_values.append(ISDValue(n, n - k, t))
        case _:
            raise Exception("Unknwon input format")

    p_range = range(1, 5)

    tot = len(isd_values) * len(p_range)

    if namespace.skip_existing:
        no_of_files = get_no_of_files(
            OUT_FILES_QLB_DIR,
            'pkl' if namespace.out_format == 'bin' else namespace.out_format)
        to_process_no = tot - no_of_files
        LOGGER.info(f"No. of already existing files: {no_of_files}")
        filter_fun = functools.partial(_process_value,
                                       out_type=out_type_dir,
                                       extension=file_ext)
        to_process_list = filter(filter_fun, isd_values)
    else:
        to_process_no = tot
        to_process_list = isd_values

    isd_compute_partial = functools.partial(isd_compute,
                                            p_range=p_range,
                                            formula=res,
                                            out_dir=out_type_dir,
                                            extension=file_ext)

    acc = 0
    if namespace.poolsize == 1:
        for _, value in enumerate(to_process_list):
            computations, _ = isd_compute_partial(value)
            acc += computations
            print(
                f"done {acc}/{to_process_no} (out of {tot}) -> {acc /to_process_no:%} ({acc /tot:%})",
                end='\r')
    else:
        with Pool(namespace.poolsize,
                  maxtasksperchild=namespace.max_tasks) as p:
            for _, result in enumerate(
                    p.imap_unordered(
                        isd_compute_partial,
                        to_process_list,
                        chunksize=namespace.chunksize,
                    )):
                computations, _ = result
                acc += computations
                print(
                    f"done {acc}/{to_process_no} (out of {tot}) -> {acc /to_process_no:%} ({acc /tot:%})",
                    end='\r')
                # LOGGER.info(
                #     f"Computed {computations}, real time: {time} seconds")

                print(
                    f"done {acc}/{to_process_no} (out of {tot}) -> {acc /to_process_no:%} ({acc /tot:%})",
                    end='\r')


if __name__ == '__main__':
    main()

# for
